/**
 * Unity Avatar Builder API
 * An API used to create custom 3D Avatars based on the OpenAPI 3.0 specification.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: katz.tricia@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */import { AccessoryModel } from './accessoryModel';


/**
 * Accessory object
 */
export interface Accessory { 
    /**
     * ID of the accessory adorning the User.
     */
    id?: number;
    /**
     * Type of the accessory adorning the User. *Possible Responses: hat, jewelry, mask, ears*
     */
    type?: Accessory.TypeEnum;
    name?: Accessory.NameEnum;
    node?: Accessory.NodeEnum;
    model?: AccessoryModel;
}
export namespace Accessory {
    export type TypeEnum = 'hat' | 'jewelry' | 'mask' | 'ears';
    export const TypeEnum = {
        Hat: 'hat' as TypeEnum,
        Jewelry: 'jewelry' as TypeEnum,
        Mask: 'mask' as TypeEnum,
        Ears: 'ears' as TypeEnum
    };
    export type NameEnum = 'cowboy' | 'magician' | 'snow' | 'pendant' | 'choker' | 'studs' | 'party' | 'superhero' | 'cartoon' | 'mouse' | 'cat' | 'bear';
    export const NameEnum = {
        Cowboy: 'cowboy' as NameEnum,
        Magician: 'magician' as NameEnum,
        Snow: 'snow' as NameEnum,
        Pendant: 'pendant' as NameEnum,
        Choker: 'choker' as NameEnum,
        Studs: 'studs' as NameEnum,
        Party: 'party' as NameEnum,
        Superhero: 'superhero' as NameEnum,
        Cartoon: 'cartoon' as NameEnum,
        Mouse: 'mouse' as NameEnum,
        Cat: 'cat' as NameEnum,
        Bear: 'bear' as NameEnum
    };
    export type NodeEnum = 'eye' | 'ear' | 'neck' | 'head';
    export const NodeEnum = {
        Eye: 'eye' as NodeEnum,
        Ear: 'ear' as NodeEnum,
        Neck: 'neck' as NodeEnum,
        Head: 'head' as NodeEnum
    };
}