/**
 * Unity Avatar Builder API
 * An API used to create custom 3D Avatars based on the OpenAPI 3.0 specification.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: katz.tricia@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface InlineResponse2001 { 
    success?: string;
}